services:
  xhs-agent:
    image: crpi-6rxq3fzaickvh3iw.cn-hangzhou.personal.cr.aliyuncs.com/xxxh/xhs_agent:latest
    container_name: xhs-agent
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./log:/app/log
